name: ex01-workflow

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *' # every day at 8am

jobs:
  author_info:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    
    - name: Fetch author name from secrets
      env:
        AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
      run: |-
        # Use the author name from secrets, fallback to default if not set
        AUTHOR="${AUTHOR_NAME:-junji+ito}"
        # Replace spaces with + for URL encoding
        AUTHOR_ENCODED=$(echo "$AUTHOR" | sed 's/ /+/g')
        echo "Fetching data for author: $AUTHOR"
        curl -s "https://openlibrary.org/search/authors.json?q=${AUTHOR_ENCODED}" > "$(date +%F)-authors.json"